# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='posttitle',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
