# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 02:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_auto_20171019_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='posttitle',
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(max_length=280),
        ),
        migrations.AlterField(
            model_name='post',
            name='description1',
            field=models.TextField(max_length=280),
        ),
        migrations.AlterField(
            model_name='post',
            name='description2',
            field=models.TextField(max_length=280),
        ),
    ]
